### ISSUE TITLE
Downloaded files are removed when building with the --no-fetch-metadata and --build-dir options

### ISSUE THREAD

**Issue by pmeulen** [pmeulen/saml-metadata-tools#1]
Reported by @salaun-renater 
Build fails when using the --no-fetch-metadata and the --build-dir options together because a previously downloaded file cannot be found. Using Scons 2.4.1.

**Comment by pmeulen** [comment]
The "--no-fetch-metadata" option is intended to allow rebuilding without re-downloading anything.

This problem was introduced in commit https://github.com/pmeulen/saml-metadata-tools/commit/e38e91b1c828e06aae420bf3bec4f2ecf5eecdb8 that makes the download dir a subdirectory of the build dir. The problem occurs because the build dir is a variant_dir with duplicate=1. Because the duplicate option duplicates files used during the build to the variant_dir it keeps a more complete record of the build in the build directory. However this option also removes files that it does not know about when it notices that these are used during the build. That is what is happening to the downloaded files.

The simplest fix seems to be to not store the downloaded files in the variant_dir, this will keep scons from removing them. We still want to keep all files used in the build (including the download directory) together. So the simplest solution would be to make the variant_dir and the download dir subdirectories of the build dir. The effect is that all target paths in the build dir change from "build_dir/some_target" to "build_dir/variant_dir/some_target"

**Comment by salaun-urennes1** [comment]
I just synced with your https://github.com/pmeulen/saml-metadata-tools/tree/fix-no-request-metadata branch and tried that code on our dev server. It works as expected. No side effects I noticed. You’re welcome to merge these changes to master.
